import type { MetadataRoute } from "next";
import { BRAND_ACCENT, BRAND_BACKGROUND, BRAND_NAME } from "@/lib/brand";

export default function manifest(): MetadataRoute.Manifest {
  return {
    name: `${BRAND_NAME} Factory QC`,
    short_name: BRAND_NAME,
    description:
      "Digital quality inspections for factories with worker, inspector, and owner workflows.",
    start_url: "/",
    display: "standalone",
    background_color: BRAND_BACKGROUND,
    theme_color: BRAND_ACCENT,
    orientation: "portrait-primary",
    // These are generated by src/app/icon.tsx and src/app/apple-icon.tsx, so
    // they serve at the extensionless route — not /icon.png.
    icons: [
      {
        src: "/icon",
        sizes: "512x512",
        type: "image/png",
        purpose: "any",
      },
      {
        src: "/apple-icon",
        sizes: "180x180",
        type: "image/png",
      },
    ],
  };
}
