-- Row-level security for every tenant-scoped table.
--
-- GENERATED by scripts/gen_rls_migration.mjs -- regenerate rather than edit.
--
-- READ BEFORE APPLYING. This migration is inert until two things are true:
--
--   1. The application connects as a role that is NOT the table owner.
--      Postgres table owners bypass RLS, so applying this while the app
--      connects as owner changes nothing and gives false assurance.
--   2. Every request sets the tenant GUCs (see src/platform/tenancy/context.ts).
--      A connection with no GUC set sees ZERO rows -- this fails closed by
--      design, so deploying the app change first is mandatory.
--
-- Migrations and seeds continue to run as the owner and are unaffected.

CREATE SCHEMA IF NOT EXISTS verity;

-- Tenant context, read from per-transaction GUCs. `true` in current_setting
-- means 'return NULL if unset' rather than raising -- combined with the
-- policies below, an unset context matches no rows.
CREATE OR REPLACE FUNCTION verity.current_factory_id() RETURNS text
  LANGUAGE sql STABLE AS $$ SELECT NULLIF(current_setting('verity.factory_id', true), '') $$;

CREATE OR REPLACE FUNCTION verity.current_org_id() RETURNS text
  LANGUAGE sql STABLE AS $$ SELECT NULLIF(current_setting('verity.org_id', true), '') $$;

-- Organization
ALTER TABLE "Organization" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Organization_tenant_isolation" ON "Organization";
CREATE POLICY "Organization_tenant_isolation" ON "Organization"
  USING ("id" = verity.current_org_id()) WITH CHECK ("id" = verity.current_org_id());

-- ModuleEntitlement
ALTER TABLE "ModuleEntitlement" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "ModuleEntitlement_tenant_isolation" ON "ModuleEntitlement";
CREATE POLICY "ModuleEntitlement_tenant_isolation" ON "ModuleEntitlement"
  USING ("organizationId" = verity.current_org_id()) WITH CHECK ("organizationId" = verity.current_org_id());

-- Factory
ALTER TABLE "Factory" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Factory_tenant_isolation" ON "Factory";
CREATE POLICY "Factory_tenant_isolation" ON "Factory"
  USING ("organizationId" = verity.current_org_id()) WITH CHECK ("organizationId" = verity.current_org_id());

-- Agreement
ALTER TABLE "Agreement" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Agreement_tenant_isolation" ON "Agreement";
CREATE POLICY "Agreement_tenant_isolation" ON "Agreement"
  USING ("factoryId" = verity.current_factory_id()) WITH CHECK ("factoryId" = verity.current_factory_id());

-- SupportSession
ALTER TABLE "SupportSession" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "SupportSession_tenant_isolation" ON "SupportSession";
CREATE POLICY "SupportSession_tenant_isolation" ON "SupportSession"
  USING ("factoryId" = verity.current_factory_id()) WITH CHECK ("factoryId" = verity.current_factory_id());

-- WorkflowStage
ALTER TABLE "WorkflowStage" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "WorkflowStage_tenant_isolation" ON "WorkflowStage";
CREATE POLICY "WorkflowStage_tenant_isolation" ON "WorkflowStage"
  USING ("factoryId" = verity.current_factory_id()) WITH CHECK ("factoryId" = verity.current_factory_id());

-- Role
ALTER TABLE "Role" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Role_tenant_isolation" ON "Role";
CREATE POLICY "Role_tenant_isolation" ON "Role"
  USING ("organizationId" = verity.current_org_id()) WITH CHECK ("organizationId" = verity.current_org_id());

-- RolePermission
ALTER TABLE "RolePermission" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "RolePermission_tenant_isolation" ON "RolePermission";
CREATE POLICY "RolePermission_tenant_isolation" ON "RolePermission"
  USING (EXISTS (SELECT 1 FROM "Role" par WHERE par."id" = "RolePermission"."roleId")) WITH CHECK (EXISTS (SELECT 1 FROM "Role" par WHERE par."id" = "RolePermission"."roleId"));

-- User
ALTER TABLE "User" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "User_tenant_isolation" ON "User";
CREATE POLICY "User_tenant_isolation" ON "User"
  USING ("factoryId" = verity.current_factory_id()) WITH CHECK ("factoryId" = verity.current_factory_id());

-- Department
ALTER TABLE "Department" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Department_tenant_isolation" ON "Department";
CREATE POLICY "Department_tenant_isolation" ON "Department"
  USING ("factoryId" = verity.current_factory_id()) WITH CHECK ("factoryId" = verity.current_factory_id());

-- TimelineEvent
ALTER TABLE "TimelineEvent" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "TimelineEvent_tenant_isolation" ON "TimelineEvent";
CREATE POLICY "TimelineEvent_tenant_isolation" ON "TimelineEvent"
  USING ("factoryId" = verity.current_factory_id()) WITH CHECK ("factoryId" = verity.current_factory_id());

-- Comment
ALTER TABLE "Comment" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Comment_tenant_isolation" ON "Comment";
CREATE POLICY "Comment_tenant_isolation" ON "Comment"
  USING ("factoryId" = verity.current_factory_id()) WITH CHECK ("factoryId" = verity.current_factory_id());

-- Attachment
ALTER TABLE "Attachment" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Attachment_tenant_isolation" ON "Attachment";
CREATE POLICY "Attachment_tenant_isolation" ON "Attachment"
  USING ("factoryId" = verity.current_factory_id()) WITH CHECK ("factoryId" = verity.current_factory_id());

-- Notification
ALTER TABLE "Notification" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Notification_tenant_isolation" ON "Notification";
CREATE POLICY "Notification_tenant_isolation" ON "Notification"
  USING ("factoryId" = verity.current_factory_id()) WITH CHECK ("factoryId" = verity.current_factory_id());

-- AuditLog
ALTER TABLE "AuditLog" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "AuditLog_tenant_isolation" ON "AuditLog";
CREATE POLICY "AuditLog_tenant_isolation" ON "AuditLog"
  USING ("factoryId" = verity.current_factory_id()) WITH CHECK ("factoryId" = verity.current_factory_id());

-- Approval
ALTER TABLE "Approval" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Approval_tenant_isolation" ON "Approval";
CREATE POLICY "Approval_tenant_isolation" ON "Approval"
  USING ("factoryId" = verity.current_factory_id()) WITH CHECK ("factoryId" = verity.current_factory_id());

-- ItemMaster
ALTER TABLE "ItemMaster" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "ItemMaster_tenant_isolation" ON "ItemMaster";
CREATE POLICY "ItemMaster_tenant_isolation" ON "ItemMaster"
  USING ("factoryId" = verity.current_factory_id()) WITH CHECK ("factoryId" = verity.current_factory_id());

-- ItemFieldDefinition
ALTER TABLE "ItemFieldDefinition" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "ItemFieldDefinition_tenant_isolation" ON "ItemFieldDefinition";
CREATE POLICY "ItemFieldDefinition_tenant_isolation" ON "ItemFieldDefinition"
  USING ("factoryId" = verity.current_factory_id()) WITH CHECK ("factoryId" = verity.current_factory_id());

-- MaterialCategory
ALTER TABLE "MaterialCategory" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "MaterialCategory_tenant_isolation" ON "MaterialCategory";
CREATE POLICY "MaterialCategory_tenant_isolation" ON "MaterialCategory"
  USING ("factoryId" = verity.current_factory_id()) WITH CHECK ("factoryId" = verity.current_factory_id());

-- MaterialSubcategory
ALTER TABLE "MaterialSubcategory" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "MaterialSubcategory_tenant_isolation" ON "MaterialSubcategory";
CREATE POLICY "MaterialSubcategory_tenant_isolation" ON "MaterialSubcategory"
  USING ("factoryId" = verity.current_factory_id()) WITH CHECK ("factoryId" = verity.current_factory_id());

-- UOMConversion
ALTER TABLE "UOMConversion" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "UOMConversion_tenant_isolation" ON "UOMConversion";
CREATE POLICY "UOMConversion_tenant_isolation" ON "UOMConversion"
  USING (EXISTS (SELECT 1 FROM "ItemMaster" par WHERE par."id" = "UOMConversion"."itemId")) WITH CHECK (EXISTS (SELECT 1 FROM "ItemMaster" par WHERE par."id" = "UOMConversion"."itemId"));

-- Warehouse
ALTER TABLE "Warehouse" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Warehouse_tenant_isolation" ON "Warehouse";
CREATE POLICY "Warehouse_tenant_isolation" ON "Warehouse"
  USING ("factoryId" = verity.current_factory_id()) WITH CHECK ("factoryId" = verity.current_factory_id());

-- WarehouseZone
ALTER TABLE "WarehouseZone" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "WarehouseZone_tenant_isolation" ON "WarehouseZone";
CREATE POLICY "WarehouseZone_tenant_isolation" ON "WarehouseZone"
  USING ("factoryId" = verity.current_factory_id()) WITH CHECK ("factoryId" = verity.current_factory_id());

-- WarehouseRack
ALTER TABLE "WarehouseRack" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "WarehouseRack_tenant_isolation" ON "WarehouseRack";
CREATE POLICY "WarehouseRack_tenant_isolation" ON "WarehouseRack"
  USING ("factoryId" = verity.current_factory_id()) WITH CHECK ("factoryId" = verity.current_factory_id());

-- WarehouseShelf
ALTER TABLE "WarehouseShelf" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "WarehouseShelf_tenant_isolation" ON "WarehouseShelf";
CREATE POLICY "WarehouseShelf_tenant_isolation" ON "WarehouseShelf"
  USING ("factoryId" = verity.current_factory_id()) WITH CHECK ("factoryId" = verity.current_factory_id());

-- WarehouseBin
ALTER TABLE "WarehouseBin" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "WarehouseBin_tenant_isolation" ON "WarehouseBin";
CREATE POLICY "WarehouseBin_tenant_isolation" ON "WarehouseBin"
  USING ("factoryId" = verity.current_factory_id()) WITH CHECK ("factoryId" = verity.current_factory_id());

-- StockLedgerEntry
ALTER TABLE "StockLedgerEntry" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "StockLedgerEntry_tenant_isolation" ON "StockLedgerEntry";
CREATE POLICY "StockLedgerEntry_tenant_isolation" ON "StockLedgerEntry"
  USING ("factoryId" = verity.current_factory_id()) WITH CHECK ("factoryId" = verity.current_factory_id());

-- BinBalance
ALTER TABLE "BinBalance" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "BinBalance_tenant_isolation" ON "BinBalance";
CREATE POLICY "BinBalance_tenant_isolation" ON "BinBalance"
  USING ("factoryId" = verity.current_factory_id()) WITH CHECK ("factoryId" = verity.current_factory_id());

-- MaterialReservation
ALTER TABLE "MaterialReservation" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "MaterialReservation_tenant_isolation" ON "MaterialReservation";
CREATE POLICY "MaterialReservation_tenant_isolation" ON "MaterialReservation"
  USING ("factoryId" = verity.current_factory_id()) WITH CHECK ("factoryId" = verity.current_factory_id());

-- SpecBOM
ALTER TABLE "SpecBOM" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "SpecBOM_tenant_isolation" ON "SpecBOM";
CREATE POLICY "SpecBOM_tenant_isolation" ON "SpecBOM"
  USING ("factoryId" = verity.current_factory_id()) WITH CHECK ("factoryId" = verity.current_factory_id());

-- Dispatch
ALTER TABLE "Dispatch" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Dispatch_tenant_isolation" ON "Dispatch";
CREATE POLICY "Dispatch_tenant_isolation" ON "Dispatch"
  USING ("factoryId" = verity.current_factory_id()) WITH CHECK ("factoryId" = verity.current_factory_id());

-- ProductCategory
ALTER TABLE "ProductCategory" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "ProductCategory_tenant_isolation" ON "ProductCategory";
CREATE POLICY "ProductCategory_tenant_isolation" ON "ProductCategory"
  USING ("factoryId" = verity.current_factory_id()) WITH CHECK ("factoryId" = verity.current_factory_id());

-- Product
ALTER TABLE "Product" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Product_tenant_isolation" ON "Product";
CREATE POLICY "Product_tenant_isolation" ON "Product"
  USING ("factoryId" = verity.current_factory_id()) WITH CHECK ("factoryId" = verity.current_factory_id());

-- ProductVariant
ALTER TABLE "ProductVariant" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "ProductVariant_tenant_isolation" ON "ProductVariant";
CREATE POLICY "ProductVariant_tenant_isolation" ON "ProductVariant"
  USING (EXISTS (SELECT 1 FROM "Product" par WHERE par."id" = "ProductVariant"."productId")) WITH CHECK (EXISTS (SELECT 1 FROM "Product" par WHERE par."id" = "ProductVariant"."productId"));

-- Blueprint
ALTER TABLE "Blueprint" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Blueprint_tenant_isolation" ON "Blueprint";
CREATE POLICY "Blueprint_tenant_isolation" ON "Blueprint"
  USING ("factoryId" = verity.current_factory_id()) WITH CHECK ("factoryId" = verity.current_factory_id());

-- BlueprintVersion
ALTER TABLE "BlueprintVersion" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "BlueprintVersion_tenant_isolation" ON "BlueprintVersion";
CREATE POLICY "BlueprintVersion_tenant_isolation" ON "BlueprintVersion"
  USING (EXISTS (SELECT 1 FROM "Blueprint" par WHERE par."id" = "BlueprintVersion"."blueprintId")) WITH CHECK (EXISTS (SELECT 1 FROM "Blueprint" par WHERE par."id" = "BlueprintVersion"."blueprintId"));

-- BlueprintRouteStep
ALTER TABLE "BlueprintRouteStep" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "BlueprintRouteStep_tenant_isolation" ON "BlueprintRouteStep";
CREATE POLICY "BlueprintRouteStep_tenant_isolation" ON "BlueprintRouteStep"
  USING (EXISTS (SELECT 1 FROM "Department" par WHERE par."id" = "BlueprintRouteStep"."departmentId")) WITH CHECK (EXISTS (SELECT 1 FROM "Department" par WHERE par."id" = "BlueprintRouteStep"."departmentId"));

-- FactoryDocument
ALTER TABLE "FactoryDocument" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "FactoryDocument_tenant_isolation" ON "FactoryDocument";
CREATE POLICY "FactoryDocument_tenant_isolation" ON "FactoryDocument"
  USING (EXISTS (SELECT 1 FROM "BlueprintVersion" par WHERE par."id" = "FactoryDocument"."blueprintVersionId")) WITH CHECK (EXISTS (SELECT 1 FROM "BlueprintVersion" par WHERE par."id" = "FactoryDocument"."blueprintVersionId"));

-- VehicleBrand
ALTER TABLE "VehicleBrand" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "VehicleBrand_tenant_isolation" ON "VehicleBrand";
CREATE POLICY "VehicleBrand_tenant_isolation" ON "VehicleBrand"
  USING ("factoryId" = verity.current_factory_id()) WITH CHECK ("factoryId" = verity.current_factory_id());

-- VehicleModel
ALTER TABLE "VehicleModel" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "VehicleModel_tenant_isolation" ON "VehicleModel";
CREATE POLICY "VehicleModel_tenant_isolation" ON "VehicleModel"
  USING ("factoryId" = verity.current_factory_id()) WITH CHECK ("factoryId" = verity.current_factory_id());

-- VehicleGeneration
ALTER TABLE "VehicleGeneration" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "VehicleGeneration_tenant_isolation" ON "VehicleGeneration";
CREATE POLICY "VehicleGeneration_tenant_isolation" ON "VehicleGeneration"
  USING ("factoryId" = verity.current_factory_id()) WITH CHECK ("factoryId" = verity.current_factory_id());

-- VehicleYear
ALTER TABLE "VehicleYear" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "VehicleYear_tenant_isolation" ON "VehicleYear";
CREATE POLICY "VehicleYear_tenant_isolation" ON "VehicleYear"
  USING ("factoryId" = verity.current_factory_id()) WITH CHECK ("factoryId" = verity.current_factory_id());

-- VehicleVariant
ALTER TABLE "VehicleVariant" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "VehicleVariant_tenant_isolation" ON "VehicleVariant";
CREATE POLICY "VehicleVariant_tenant_isolation" ON "VehicleVariant"
  USING ("factoryId" = verity.current_factory_id()) WITH CHECK ("factoryId" = verity.current_factory_id());

-- ProductVehicleFitment
ALTER TABLE "ProductVehicleFitment" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "ProductVehicleFitment_tenant_isolation" ON "ProductVehicleFitment";
CREATE POLICY "ProductVehicleFitment_tenant_isolation" ON "ProductVehicleFitment"
  USING ("factoryId" = verity.current_factory_id()) WITH CHECK ("factoryId" = verity.current_factory_id());

-- Supplier
ALTER TABLE "Supplier" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Supplier_tenant_isolation" ON "Supplier";
CREATE POLICY "Supplier_tenant_isolation" ON "Supplier"
  USING ("factoryId" = verity.current_factory_id()) WITH CHECK ("factoryId" = verity.current_factory_id());

-- PurchaseRequest
ALTER TABLE "PurchaseRequest" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "PurchaseRequest_tenant_isolation" ON "PurchaseRequest";
CREATE POLICY "PurchaseRequest_tenant_isolation" ON "PurchaseRequest"
  USING ("factoryId" = verity.current_factory_id()) WITH CHECK ("factoryId" = verity.current_factory_id());

-- PurchaseOrder
ALTER TABLE "PurchaseOrder" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "PurchaseOrder_tenant_isolation" ON "PurchaseOrder";
CREATE POLICY "PurchaseOrder_tenant_isolation" ON "PurchaseOrder"
  USING ("factoryId" = verity.current_factory_id()) WITH CHECK ("factoryId" = verity.current_factory_id());

-- PurchaseOrderItem
ALTER TABLE "PurchaseOrderItem" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "PurchaseOrderItem_tenant_isolation" ON "PurchaseOrderItem";
CREATE POLICY "PurchaseOrderItem_tenant_isolation" ON "PurchaseOrderItem"
  USING (EXISTS (SELECT 1 FROM "PurchaseOrder" par WHERE par."id" = "PurchaseOrderItem"."purchaseOrderId")) WITH CHECK (EXISTS (SELECT 1 FROM "PurchaseOrder" par WHERE par."id" = "PurchaseOrderItem"."purchaseOrderId"));

-- PurchaseReceipt
ALTER TABLE "PurchaseReceipt" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "PurchaseReceipt_tenant_isolation" ON "PurchaseReceipt";
CREATE POLICY "PurchaseReceipt_tenant_isolation" ON "PurchaseReceipt"
  USING ("factoryId" = verity.current_factory_id()) WITH CHECK ("factoryId" = verity.current_factory_id());

-- PurchaseReceiptItem
ALTER TABLE "PurchaseReceiptItem" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "PurchaseReceiptItem_tenant_isolation" ON "PurchaseReceiptItem";
CREATE POLICY "PurchaseReceiptItem_tenant_isolation" ON "PurchaseReceiptItem"
  USING (EXISTS (SELECT 1 FROM "PurchaseReceipt" par WHERE par."id" = "PurchaseReceiptItem"."receiptId")) WITH CHECK (EXISTS (SELECT 1 FROM "PurchaseReceipt" par WHERE par."id" = "PurchaseReceiptItem"."receiptId"));

-- PurchaseInvoice
ALTER TABLE "PurchaseInvoice" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "PurchaseInvoice_tenant_isolation" ON "PurchaseInvoice";
CREATE POLICY "PurchaseInvoice_tenant_isolation" ON "PurchaseInvoice"
  USING ("factoryId" = verity.current_factory_id()) WITH CHECK ("factoryId" = verity.current_factory_id());

-- BOM
ALTER TABLE "BOM" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "BOM_tenant_isolation" ON "BOM";
CREATE POLICY "BOM_tenant_isolation" ON "BOM"
  USING ("factoryId" = verity.current_factory_id()) WITH CHECK ("factoryId" = verity.current_factory_id());

-- BOMItem
ALTER TABLE "BOMItem" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "BOMItem_tenant_isolation" ON "BOMItem";
CREATE POLICY "BOMItem_tenant_isolation" ON "BOMItem"
  USING (EXISTS (SELECT 1 FROM "BOM" par WHERE par."id" = "BOMItem"."bomId")) WITH CHECK (EXISTS (SELECT 1 FROM "BOM" par WHERE par."id" = "BOMItem"."bomId"));

-- ProductionPlan
ALTER TABLE "ProductionPlan" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "ProductionPlan_tenant_isolation" ON "ProductionPlan";
CREATE POLICY "ProductionPlan_tenant_isolation" ON "ProductionPlan"
  USING ("factoryId" = verity.current_factory_id()) WITH CHECK ("factoryId" = verity.current_factory_id());

-- WorkOrder
ALTER TABLE "WorkOrder" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "WorkOrder_tenant_isolation" ON "WorkOrder";
CREATE POLICY "WorkOrder_tenant_isolation" ON "WorkOrder"
  USING ("factoryId" = verity.current_factory_id()) WITH CHECK ("factoryId" = verity.current_factory_id());

-- JobCard
ALTER TABLE "JobCard" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "JobCard_tenant_isolation" ON "JobCard";
CREATE POLICY "JobCard_tenant_isolation" ON "JobCard"
  USING ("factoryId" = verity.current_factory_id()) WITH CHECK ("factoryId" = verity.current_factory_id());

-- StageEntry
ALTER TABLE "StageEntry" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "StageEntry_tenant_isolation" ON "StageEntry";
CREATE POLICY "StageEntry_tenant_isolation" ON "StageEntry"
  USING ("factoryId" = verity.current_factory_id()) WITH CHECK ("factoryId" = verity.current_factory_id());

-- Customer
ALTER TABLE "Customer" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Customer_tenant_isolation" ON "Customer";
CREATE POLICY "Customer_tenant_isolation" ON "Customer"
  USING ("factoryId" = verity.current_factory_id()) WITH CHECK ("factoryId" = verity.current_factory_id());

-- Deal
ALTER TABLE "Deal" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Deal_tenant_isolation" ON "Deal";
CREATE POLICY "Deal_tenant_isolation" ON "Deal"
  USING ("factoryId" = verity.current_factory_id()) WITH CHECK ("factoryId" = verity.current_factory_id());

-- SalesOrder
ALTER TABLE "SalesOrder" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "SalesOrder_tenant_isolation" ON "SalesOrder";
CREATE POLICY "SalesOrder_tenant_isolation" ON "SalesOrder"
  USING ("factoryId" = verity.current_factory_id()) WITH CHECK ("factoryId" = verity.current_factory_id());

-- Design
ALTER TABLE "Design" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Design_tenant_isolation" ON "Design";
CREATE POLICY "Design_tenant_isolation" ON "Design"
  USING ("factoryId" = verity.current_factory_id()) WITH CHECK ("factoryId" = verity.current_factory_id());

-- Color
ALTER TABLE "Color" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Color_tenant_isolation" ON "Color";
CREATE POLICY "Color_tenant_isolation" ON "Color"
  USING ("factoryId" = verity.current_factory_id()) WITH CHECK ("factoryId" = verity.current_factory_id());

-- ProductCombination
ALTER TABLE "ProductCombination" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "ProductCombination_tenant_isolation" ON "ProductCombination";
CREATE POLICY "ProductCombination_tenant_isolation" ON "ProductCombination"
  USING ("factoryId" = verity.current_factory_id()) WITH CHECK ("factoryId" = verity.current_factory_id());

-- ProductType
ALTER TABLE "ProductType" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "ProductType_tenant_isolation" ON "ProductType";
CREATE POLICY "ProductType_tenant_isolation" ON "ProductType"
  USING ("factoryId" = verity.current_factory_id()) WITH CHECK ("factoryId" = verity.current_factory_id());

-- ProductField
ALTER TABLE "ProductField" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "ProductField_tenant_isolation" ON "ProductField";
CREATE POLICY "ProductField_tenant_isolation" ON "ProductField"
  USING (EXISTS (SELECT 1 FROM "ProductType" par WHERE par."id" = "ProductField"."productTypeId")) WITH CHECK (EXISTS (SELECT 1 FROM "ProductType" par WHERE par."id" = "ProductField"."productTypeId"));

-- ProductionBatch
ALTER TABLE "ProductionBatch" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "ProductionBatch_tenant_isolation" ON "ProductionBatch";
CREATE POLICY "ProductionBatch_tenant_isolation" ON "ProductionBatch"
  USING ("factoryId" = verity.current_factory_id()) WITH CHECK ("factoryId" = verity.current_factory_id());

-- SalesOrderItem
ALTER TABLE "SalesOrderItem" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "SalesOrderItem_tenant_isolation" ON "SalesOrderItem";
CREATE POLICY "SalesOrderItem_tenant_isolation" ON "SalesOrderItem"
  USING (EXISTS (SELECT 1 FROM "SalesOrder" par WHERE par."id" = "SalesOrderItem"."salesOrderId")) WITH CHECK (EXISTS (SELECT 1 FROM "SalesOrder" par WHERE par."id" = "SalesOrderItem"."salesOrderId"));

-- EmployeeProfile
ALTER TABLE "EmployeeProfile" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "EmployeeProfile_tenant_isolation" ON "EmployeeProfile";
CREATE POLICY "EmployeeProfile_tenant_isolation" ON "EmployeeProfile"
  USING ("factoryId" = verity.current_factory_id()) WITH CHECK ("factoryId" = verity.current_factory_id());

-- Shift
ALTER TABLE "Shift" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Shift_tenant_isolation" ON "Shift";
CREATE POLICY "Shift_tenant_isolation" ON "Shift"
  USING ("factoryId" = verity.current_factory_id()) WITH CHECK ("factoryId" = verity.current_factory_id());

-- AttendanceLog
ALTER TABLE "AttendanceLog" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "AttendanceLog_tenant_isolation" ON "AttendanceLog";
CREATE POLICY "AttendanceLog_tenant_isolation" ON "AttendanceLog"
  USING ("factoryId" = verity.current_factory_id()) WITH CHECK ("factoryId" = verity.current_factory_id());

-- LeaveApplication
ALTER TABLE "LeaveApplication" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "LeaveApplication_tenant_isolation" ON "LeaveApplication";
CREATE POLICY "LeaveApplication_tenant_isolation" ON "LeaveApplication"
  USING ("factoryId" = verity.current_factory_id()) WITH CHECK ("factoryId" = verity.current_factory_id());

-- QCTemplate
ALTER TABLE "QCTemplate" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "QCTemplate_tenant_isolation" ON "QCTemplate";
CREATE POLICY "QCTemplate_tenant_isolation" ON "QCTemplate"
  USING ("factoryId" = verity.current_factory_id()) WITH CHECK ("factoryId" = verity.current_factory_id());

-- TemplateSection
ALTER TABLE "TemplateSection" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "TemplateSection_tenant_isolation" ON "TemplateSection";
CREATE POLICY "TemplateSection_tenant_isolation" ON "TemplateSection"
  USING ("factoryId" = verity.current_factory_id()) WITH CHECK ("factoryId" = verity.current_factory_id());

-- Checkpoint
ALTER TABLE "Checkpoint" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Checkpoint_tenant_isolation" ON "Checkpoint";
CREATE POLICY "Checkpoint_tenant_isolation" ON "Checkpoint"
  USING ("factoryId" = verity.current_factory_id()) WITH CHECK ("factoryId" = verity.current_factory_id());

-- Inspection
ALTER TABLE "Inspection" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Inspection_tenant_isolation" ON "Inspection";
CREATE POLICY "Inspection_tenant_isolation" ON "Inspection"
  USING ("factoryId" = verity.current_factory_id()) WITH CHECK ("factoryId" = verity.current_factory_id());

-- CheckpointSubmission
ALTER TABLE "CheckpointSubmission" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "CheckpointSubmission_tenant_isolation" ON "CheckpointSubmission";
CREATE POLICY "CheckpointSubmission_tenant_isolation" ON "CheckpointSubmission"
  USING ("factoryId" = verity.current_factory_id()) WITH CHECK ("factoryId" = verity.current_factory_id());

-- ImageEvidence
ALTER TABLE "ImageEvidence" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "ImageEvidence_tenant_isolation" ON "ImageEvidence";
CREATE POLICY "ImageEvidence_tenant_isolation" ON "ImageEvidence"
  USING ("factoryId" = verity.current_factory_id()) WITH CHECK ("factoryId" = verity.current_factory_id());

-- QualityApproval
ALTER TABLE "QualityApproval" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "QualityApproval_tenant_isolation" ON "QualityApproval";
CREATE POLICY "QualityApproval_tenant_isolation" ON "QualityApproval"
  USING ("factoryId" = verity.current_factory_id()) WITH CHECK ("factoryId" = verity.current_factory_id());

-- QualityReport
ALTER TABLE "QualityReport" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "QualityReport_tenant_isolation" ON "QualityReport";
CREATE POLICY "QualityReport_tenant_isolation" ON "QualityReport"
  USING ("factoryId" = verity.current_factory_id()) WITH CHECK ("factoryId" = verity.current_factory_id());

-- ReworkRecord
ALTER TABLE "ReworkRecord" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "ReworkRecord_tenant_isolation" ON "ReworkRecord";
CREATE POLICY "ReworkRecord_tenant_isolation" ON "ReworkRecord"
  USING ("factoryId" = verity.current_factory_id()) WITH CHECK ("factoryId" = verity.current_factory_id());

-- Covered: 65 factory-scoped, 4 org-scoped, 11 via parent.