// Generates the row-level-security migration from the Prisma schema.
//
// Kept as a script rather than hand-written SQL because the policy set must
// cover every tenant-scoped table, and the schema has 80 of them. A hand
// list would drift the first time somebody adds a model.
//
// Run: node scripts/gen_rls_migration.mjs > <migration>/migration.sql

import fs from "node:fs";

const schema = fs.readFileSync("prisma/schema.prisma", "utf8");
const models = [...schema.matchAll(/model\s+(\w+)\s*\{([\s\S]*?)\n\}/g)].map((m) => ({
  name: m[1],
  body: m[2],
}));

const has = (body, field) => new RegExp(`^\\s*${field}\\s`, "m").test(body);

// Child tables carry no tenant column; they are reached only through a parent.
// Each maps to [parentTable, localFkColumn]. Without these the child tables are
// readable by primary key alone, which is exactly the leak RLS is meant to close.
const CHILD_PARENT = {
  RolePermission: ["Role", "roleId"],
  ProductField: ["ProductType", "productTypeId"],
  SalesOrderItem: ["SalesOrder", "orderId"],
  PurchaseOrderItem: ["PurchaseOrder", "purchaseOrderId"],
  PurchaseReceiptItem: ["PurchaseReceipt", "receiptId"],
  BOMItem: ["BOM", "bomId"],
  BlueprintVersion: ["Blueprint", "blueprintId"],
  BlueprintRouteStep: ["BlueprintVersion", "versionId"],
  ProductVariant: ["Product", "productId"],
  FactoryDocument: ["Factory", "factoryId"],
  UOMConversion: ["ItemMaster", "itemId"],
};

const out = [];
const p = (s = "") => out.push(s);

p("-- Row-level security for every tenant-scoped table.");
p("--");
p("-- GENERATED by scripts/gen_rls_migration.mjs -- regenerate rather than edit.");
p("--");
p("-- READ BEFORE APPLYING. This migration is inert until two things are true:");
p("--");
p("--   1. The application connects as a role that is NOT the table owner.");
p("--      Postgres table owners bypass RLS, so applying this while the app");
p("--      connects as owner changes nothing and gives false assurance.");
p("--   2. Every request sets the tenant GUCs (see src/platform/tenancy/context.ts).");
p("--      A connection with no GUC set sees ZERO rows -- this fails closed by");
p("--      design, so deploying the app change first is mandatory.");
p("--");
p("-- Migrations and seeds continue to run as the owner and are unaffected.");
p("");
p("CREATE SCHEMA IF NOT EXISTS verity;");
p("");
p("-- Tenant context, read from per-transaction GUCs. `true` in current_setting");
p("-- means 'return NULL if unset' rather than raising -- combined with the");
p("-- policies below, an unset context matches no rows.");
p("CREATE OR REPLACE FUNCTION verity.current_factory_id() RETURNS text");
p("  LANGUAGE sql STABLE AS $$ SELECT NULLIF(current_setting('verity.factory_id', true), '') $$;");
p("");
p("CREATE OR REPLACE FUNCTION verity.current_org_id() RETURNS text");
p("  LANGUAGE sql STABLE AS $$ SELECT NULLIF(current_setting('verity.org_id', true), '') $$;");
p("");

const emit = (table, predicate) => {
  p(`-- ${table}`);
  p(`ALTER TABLE "${table}" ENABLE ROW LEVEL SECURITY;`);
  p(`DROP POLICY IF EXISTS "${table}_tenant_isolation" ON "${table}";`);
  p(`CREATE POLICY "${table}_tenant_isolation" ON "${table}"`);
  p(`  USING (${predicate}) WITH CHECK (${predicate});`);
  p("");
};

const factoryScoped = [];
const orgScoped = [];
const childScoped = [];

for (const { name, body } of models) {
  if (name === "Organization") {
    orgScoped.push(name);
    emit(name, `"id" = verity.current_org_id()`);
  } else if (has(body, "factoryId")) {
    factoryScoped.push(name);
    emit(name, `"factoryId" = verity.current_factory_id()`);
  } else if (has(body, "organizationId")) {
    orgScoped.push(name);
    emit(name, `"organizationId" = verity.current_org_id()`);
  } else if (CHILD_PARENT[name]) {
    const [parent, fk] = CHILD_PARENT[name];
    childScoped.push(name);
    // Recursive containment: the parent's own policy applies to this EXISTS,
    // so a child is visible exactly when its parent is.
    emit(
      name,
      `EXISTS (SELECT 1 FROM "${parent}" par WHERE par."id" = "${name}"."${fk}")`,
    );
  } else {
    p(`-- SKIPPED ${name}: no tenant column and no parent mapping. Add one to`);
    p(`-- CHILD_PARENT in scripts/gen_rls_migration.mjs before shipping.`);
    p("");
  }
}

p(`-- Covered: ${factoryScoped.length} factory-scoped, ${orgScoped.length} org-scoped, ${childScoped.length} via parent.`);

process.stdout.write(out.join("\n"));
