// Generates the row-level-security migration from the Prisma schema.
//
// Kept as a script rather than hand-written SQL because the policy set must
// cover every tenant-scoped table, and the schema has 80 of them. A hand list
// would drift the first time somebody adds a model.
//
// Parent foreign keys are DERIVED from the schema, not hardcoded. An earlier
// version guessed them and got three wrong (SalesOrderItem.orderId,
// BlueprintRouteStep.versionId, and FactoryDocument->Factory, which has no
// factoryId at all), which only surfaced when the migration hit the database.
//
// Run: node scripts/gen_rls_migration.mjs > <migration>/migration.sql

import fs from "node:fs";

const schema = fs.readFileSync("prisma/schema.prisma", "utf8");

const models = [...schema.matchAll(/model\s+(\w+)\s*\{([\s\S]*?)\n\}/g)].map((m) => ({
  name: m[1],
  body: m[2],
}));
const byName = new Map(models.map((m) => [m.name, m]));

const hasField = (body, field) => new RegExp(`^\\s*${field}\\s`, "m").test(body);

/** Relations declared on a model: [{ target, fk }]. */
function relations(body) {
  const out = [];
  const re =
    /^\s*(\w+)\s+(\w+)(\?|\[\])?\s*@relation\((?:"[^"]*",\s*)?fields:\s*\[([^\]]+)\],\s*references:\s*\[[^\]]+\]/gm;
  for (const m of body.matchAll(re)) {
    out.push({ target: m[2], fk: m[4].trim() });
  }
  return out;
}

const scopeOf = new Map(); // model -> "factory" | "org" | "child" | "none"

for (const { name, body } of models) {
  if (name === "Organization") scopeOf.set(name, "org-self");
  else if (hasField(body, "factoryId")) scopeOf.set(name, "factory");
  else if (hasField(body, "organizationId")) scopeOf.set(name, "org");
}

/**
 * For an unscoped model, find the relation that leads to a scoped ancestor.
 * Self-references (ProductField.parentFieldId) are skipped — they lead nowhere
 * and would produce a policy that depends on itself.
 */
function parentLink(name) {
  const model = byName.get(name);
  if (!model) return null;

  const rels = relations(model.body).filter((r) => r.target !== name);

  // Prefer a directly scoped parent, then one that is itself resolvable.
  const direct = rels.find((r) => scopeOf.has(r.target));
  if (direct) return direct;

  return rels.find((r) => byName.has(r.target) && parentLinkShallow(r.target)) ?? null;
}

function parentLinkShallow(name) {
  const model = byName.get(name);
  if (!model) return null;
  return relations(model.body).some((r) => r.target !== name && scopeOf.has(r.target));
}

const out = [];
const p = (s = "") => out.push(s);

p("-- Row-level security for every tenant-scoped table.");
p("--");
p("-- GENERATED by scripts/gen_rls_migration.mjs -- regenerate rather than edit.");
p("--");
p("-- READ BEFORE APPLYING. This migration is inert until two things are true:");
p("--");
p("--   1. The application connects as a role that is NOT the table owner.");
p("--      Postgres table owners bypass RLS, so applying this while the app");
p("--      connects as owner changes nothing and gives false assurance.");
p("--   2. Every request sets the tenant GUCs (see src/platform/tenancy/context.ts).");
p("--      A connection with no GUC set sees ZERO rows -- this fails closed by");
p("--      design, so deploying the app change first is mandatory.");
p("--");
p("-- Migrations and seeds continue to run as the owner and are unaffected.");
p("");
p("CREATE SCHEMA IF NOT EXISTS verity;");
p("");
p("-- Tenant context, read from per-transaction GUCs. `true` in current_setting");
p("-- means 'return NULL if unset' rather than raising -- combined with the");
p("-- policies below, an unset context matches no rows.");
p("CREATE OR REPLACE FUNCTION verity.current_factory_id() RETURNS text");
p("  LANGUAGE sql STABLE AS $$ SELECT NULLIF(current_setting('verity.factory_id', true), '') $$;");
p("");
p("CREATE OR REPLACE FUNCTION verity.current_org_id() RETURNS text");
p("  LANGUAGE sql STABLE AS $$ SELECT NULLIF(current_setting('verity.org_id', true), '') $$;");
p("");

const emit = (table, predicate) => {
  p(`-- ${table}`);
  p(`ALTER TABLE "${table}" ENABLE ROW LEVEL SECURITY;`);
  p(`DROP POLICY IF EXISTS "${table}_tenant_isolation" ON "${table}";`);
  p(`CREATE POLICY "${table}_tenant_isolation" ON "${table}"`);
  p(`  USING (${predicate}) WITH CHECK (${predicate});`);
  p("");
};

const counts = { factory: 0, org: 0, child: 0, skipped: [] };

for (const { name } of models) {
  const scope = scopeOf.get(name);

  if (scope === "org-self") {
    counts.org++;
    emit(name, `"id" = verity.current_org_id()`);
  } else if (scope === "factory") {
    counts.factory++;
    emit(name, `"factoryId" = verity.current_factory_id()`);
  } else if (scope === "org") {
    counts.org++;
    emit(name, `"organizationId" = verity.current_org_id()`);
  } else {
    const link = parentLink(name);
    if (link) {
      counts.child++;
      // Containment: the parent's own policy applies inside this EXISTS, so a
      // child row is visible exactly when its parent is.
      emit(
        name,
        `EXISTS (SELECT 1 FROM "${link.target}" par WHERE par."id" = "${name}"."${link.fk}")`,
      );
    } else {
      counts.skipped.push(name);
      p(`-- SKIPPED ${name}: no tenant column and no resolvable parent relation.`);
      p("");
    }
  }
}

p(
  `-- Covered: ${counts.factory} factory-scoped, ${counts.org} org-scoped, ${counts.child} via parent.` +
    (counts.skipped.length ? ` SKIPPED: ${counts.skipped.join(", ")}` : ""),
);

if (counts.skipped.length) {
  process.stderr.write(`WARNING unscoped tables: ${counts.skipped.join(", ")}\n`);
}

process.stdout.write(out.join("\n"));
